# Tokyonight
# Theme create by: https://github.com/pearcidar
# Update by(sort by time):
# 
# Thanks for all contributor!!

# If you want to make border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "catppuccin-macchiato"

# ========= Border =========
file_panel_border = "#ff94e2"
sidebar_border = "#55e6d7"
footer_border = "#4e8fcc"

# ========= Border Active =========
file_panel_border_active = "#ff6186"
sidebar_border_active = "#ff6186"
footer_border_active = "#ff6186"
modal_border_active = "#ff6186"

# ========= Background (bg) =========
full_screen_bg = "#1a1b26"
file_panel_bg = "#1a1b26"
sidebar_bg = "#1a1b26"
footer_bg = "#1a1b26"
modal_bg = "#1a1b26"

# ========= Foreground (fg) =========
full_screen_fg = "#80ccff"
file_panel_fg = "#80ccff"
sidebar_fg = "#80ccff"
footer_fg = "#80ccff"
modal_fg = "#80ccff"

# ========= Special Color =========
cursor = "#149bf5"
correct = "#9ece6a"
error = "#f7768e"
hint = "#7dcfff"
cancel = "#ff9e64"
# Gradient color can only have two color!
gradient_color = ["#7aa2f7", "#bb9af7"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#73daca"
file_panel_top_path = "#7aa2f7"
file_panel_item_selected_fg = "#ff6186"
file_panel_item_selected_bg = "#1a1b26"

# ========= Sidebar Special Items =========
sidebar_title = "#73daca"
sidebar_item_selected_fg = "#7dcfff"
sidebar_item_selected_bg = "#1a1b26"
sidebar_divider = "#565f89"

# ========= Modal Special Items =========
modal_cancel_fg = "#24383b"
modal_cancel_bg = "#e0af68"

modal_confirm_fg = "#24283b"
modal_confirm_bg = "#9ece6a"

# ========= Help Menu =========
help_menu_hotkey = "#7dcfff"
help_menu_title = "#73daca"
